name: Deploy Flask App to AWS ECS

on:
  push:
    branches:
      - master

env:
   AWS_REGION: ${{secrets.AWS_REGION }}
   ECR_REPO_NAME: ${{secrets.ECR_REPOSITORY }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-d: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v2

    
